---
name: Container Build

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |-
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.VERSION }}
