apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubedoom
  name: kubedoom
  namespace: kubedoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      serviceAccountName: kubedoom
      containers:
        - image: ghcr.io/storax/kubedoom@sha256:851ba8c80b93cd518e06111a17bca12c40ade062d727cad21e4a690779dd5445
          name: kubedoom
          ports:
            - containerPort: 5900
              name: vnc
          envFrom:
            - configMapRef:
                name: kubedoom-config
          resources:
            requests:
              memory: "$(KUBE_DOOM_MEM_REQUEST)"
              cpu: "$(KUBE_DOOM_CPU_REQUEST)"
            limits:
              memory: "$(KUBE_DOOM_MEM_LIMIT)"
              cpu: "$(KUBE_DOOM_CPU_LIMIT)"
        - image: geek1011/easy-novnc@sha256:c79d386dd660533106a65473650fcf5ddc61319d02183f76c0009349d5dd5ee8
          args:
            - --basic-ui
            - --verbose
            - --no-url-password
          name: easy-novnc
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: kubedoom-config
          resources:
            requests:
              memory: "$(EASY_NOVNC_MEM_REQUEST)"
              cpu: "$(EASY_NOVNC_CPU_REQUEST)"
            limits:
              memory: "$(EASY_NOVNC_MEM_LIMIT)"
              cpu: "$(EASY_NOVNC_CPU_LIMIT)"