---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom-blue
  namespace: kubedoom
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: ~
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom-orange
  namespace: kubedoom
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: ~
