name: Lint Code Base and Auto-Merge

on:
  push:
    branches-ignore: [main, master]

jobs:
  lint_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "Apply lint fixes" || echo "No changes to commit"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Apply lint fixes"
          title: "Apply lint fixes"
          body: "This PR applies lint fixes to the codebase."
          branch: "lint-fixes"
          base: main
          labels: "lint-fixes"

  auto_merge:
    needs: lint_and_create_pr
    runs-on: ubuntu-latest
    if: ${{ steps.lint_and_create_pr.outputs.pull-request-number }}
    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.14.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "lint-fixes"
          UPDATE_LABELS: ""
          MERGE_COMMIT_MESSAGE: "Automatically merge lint fixes"
          MERGE_METHOD: "squash"
