name: Create and publish a Container Image

on:
  push:
    branches: [master, main]
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  auto-versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: false

  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=sha,format=long,prefix=
      - name: Save metadata to file
        run: |
          echo "${{ steps.meta.outputs.tags }}" > tags.txt
          echo "${{ steps.meta.outputs.labels }}" > labels.txt
      - name: Upload metadata
        uses: actions/upload-artifact@v3.12
        with:
          name: metadata
          path: |
            tags.txt
            labels.txt

      - name: Build Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          platforms: linux/amd64, linux/arm64
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  push-image:
    needs: build-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download metadata
        uses: actions/download-artifact@v2
        with:
          name: metadata
      - name: Load metadata from file
        id: load_metadata
        run: |
          echo "TAGS=$(cat tags.txt)" >> $GITHUB_ENV
          echo "LABELS=$(cat labels.txt)" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          platforms: linux/amd64, linux/arm64
          context: .
          push: true
          tags: ${{ env.TAGS }}
          labels: ${{ env.LABELS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    needs: push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release and Upload Changelog
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          name: Release ${{ steps.create_tag.outputs.new_version }}
          body: |
            ${{ env.IMAGE_NAME }} version ${{ steps.create_tag.outputs.new_version }} is now available.

            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.create_tag.outputs.new_version }}
          draft: false
          prerelease: false
          files: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
