name: Prune Old Container Images

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Prune old images
        uses: freefair/action-ghcr-prune@v0.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: ${{ github.event.repository.name }}
          dry-run: false
          older-than: 7 # days
          keep-last: 3
          untagged: true
